-- Question bank for topic-picker suggestions (189 reviewed questions).
-- Generated from question-bank/grade-*-question-bank.csv (human-reviewed).
-- served_suggestions tracks which questions each user has seen (no repeats).

create table if not exists question_bank (
  id         serial primary key,
  topic_id   text not null,
  topic      text not null,
  band       text not null,
  level      text not null,
  question   text not null,
  answer     text,
  source     text not null default 'reviewed_generated',
  created_at timestamptz default now()
);
create index if not exists idx_qbank_topic on question_bank (topic_id, band, level);

create table if not exists served_suggestions (
  user_id     uuid references auth.users(id) on delete cascade,
  question_id int references question_bank(id) on delete cascade,
  served_at   timestamptz default now(),
  primary key (user_id, question_id)
);
create index if not exists idx_served_user on served_suggestions (user_id, served_at);

insert into question_bank (topic_id, topic, band, level, question, answer) values
('quadratics','Quadratic Equations','10-11','easy','Solve: x^2 = 49','x = 7 or x = −7'),
('quadratics','Quadratic Equations','10-11','easy','Solve: x^2 − 5x = 0','x = 0 or x = 5'),
('quadratics','Quadratic Equations','10-11','easy','Solve: x^2 − 9 = 0','x = 3 or x = −3'),
('quadratics','Quadratic Equations','10-11','medium','Solve: x^2 − 7x + 12 = 0','x = 3 or x = 4'),
('quadratics','Quadratic Equations','10-11','medium','Solve: x^2 + 2x − 15 = 0','x = −5 or x = 3'),
('quadratics','Quadratic Equations','10-11','medium','Find the discriminant of x^2 − 6x + 9 = 0. What does it tell you about the roots?','0; roots are real and equal'),
('quadratics','Quadratic Equations','10-11','challenge','Solve: 2x^2 − 5x − 3 = 0','x = 3 or x = −1/2'),
('quadratics','Quadratic Equations','10-11','challenge','Without solving, find the sum and product of the roots of x^2 − 8x + 5 = 0.','Sum = 8, product = 5'),
('quadratics','Quadratic Equations','10-11','challenge','The product of two consecutive positive integers is 156. Find the integers.','12 and 13'),
('systems-equations','Systems of Equations','10-11','easy','Solve: x + y = 10 and x − y = 4','x = 7, y = 3'),
('systems-equations','Systems of Equations','10-11','easy','Solve: y = 2x and x + y = 12','x = 4, y = 8'),
('systems-equations','Systems of Equations','10-11','easy','Solve: 2x + y = 7 and y = 1','x = 3, y = 1'),
('systems-equations','Systems of Equations','10-11','medium','Solve: 2x + 3y = 12 and x − y = 1','x = 3, y = 2'),
('systems-equations','Systems of Equations','10-11','medium','Solve: x + 2y = 8 and 2x − y = 6','x = 4, y = 2'),
('systems-equations','Systems of Equations','10-11','medium','Two pens and three pencils cost 24. One pen and two pencils cost 14. Find the cost of one pen and one pencil.','Pen = 6, pencil = 4'),
('systems-equations','Systems of Equations','10-11','challenge','Solve: 3x − 2y = 5 and 2x + 5y = 16','x = 3, y = 2'),
('systems-equations','Systems of Equations','10-11','challenge','The digits of a two-digit number add up to 11. Reversing the digits gives a number 27 more than the original. Find the number.','47'),
('systems-equations','Systems of Equations','10-11','challenge','A boat travels 30 km downstream in 2 hours and returns upstream in 3 hours. Find the speed of the boat in still water and the speed of the stream.','Boat = 12.5 km/h, stream = 2.5 km/h'),
('trigonometry','Trigonometry','10-11','easy','Find the value of sin 30°.','1/2'),
('trigonometry','Trigonometry','10-11','easy','Find the value of tan 45°.','1'),
('trigonometry','Trigonometry','10-11','easy','Find the value of cos 60°.','1/2'),
('trigonometry','Trigonometry','10-11','medium','If sin θ = 3/5 and θ is acute, find cos θ.','4/5'),
('trigonometry','Trigonometry','10-11','medium','Evaluate: sin^230° + cos^230°','1'),
('trigonometry','Trigonometry','10-11','medium','Evaluate: tan 30° × tan 60°','1'),
('trigonometry','Trigonometry','10-11','challenge','From a point 60 m from the base of a tower, the angle of elevation of the top is 30°. Find the height of the tower.','20√3 m (≈ 34.6 m)'),
('trigonometry','Trigonometry','10-11','challenge','If tan θ = 1 and θ is acute, find sin θ + cos θ.','√2'),
('trigonometry','Trigonometry','10-11','challenge','Evaluate: sin 60° cos 30° + cos 60° sin 30°','1'),
('coordinate-geometry','Coordinate Geometry','10-11','easy','Find the distance between (0, 0) and (3, 4).','5'),
('coordinate-geometry','Coordinate Geometry','10-11','easy','In which quadrant does the point (−2, 5) lie?','Second quadrant'),
('coordinate-geometry','Coordinate Geometry','10-11','easy','Find the midpoint of (2, 4) and (6, 8).','(4, 6)'),
('coordinate-geometry','Coordinate Geometry','10-11','medium','Find the distance between (1, 2) and (7, 10).','10'),
('coordinate-geometry','Coordinate Geometry','10-11','medium','Find the slope of the line through (2, 3) and (6, 11).','2'),
('coordinate-geometry','Coordinate Geometry','10-11','medium','Find the point on the x-axis equidistant from (2, −5) and (−2, 9).','(−7, 0)'),
('coordinate-geometry','Coordinate Geometry','10-11','challenge','A triangle has vertices (0, 0), (4, 0) and (4, 3). Find its perimeter.','12'),
('coordinate-geometry','Coordinate Geometry','10-11','challenge','The distance between (3, y) and (3, −2) is 7. Find the possible values of y.','y = 5 or y = −9'),
('coordinate-geometry','Coordinate Geometry','10-11','challenge','In what ratio does the point (2, 5) divide the line segment from (1, 3) to (4, 9)?','1 : 2'),
('functions-graphs','Functions & Graphs','10-11','easy','If f(x) = 2x + 3, find f(4).','11'),
('functions-graphs','Functions & Graphs','10-11','easy','If f(x) = x^2, find f(−3).','9'),
('functions-graphs','Functions & Graphs','10-11','easy','What is the y-intercept of the line y = 3x − 2?','−2'),
('functions-graphs','Functions & Graphs','10-11','medium','If f(x) = x^2 − 2x, find f(5).','15'),
('functions-graphs','Functions & Graphs','10-11','medium','State the slope and y-intercept of y = −2x + 7.','Slope = −2, y-intercept = 7'),
('functions-graphs','Functions & Graphs','10-11','medium','If f(x) = 3x − 1 and f(a) = 14, find a.','a = 5'),
('functions-graphs','Functions & Graphs','10-11','challenge','If f(x) = 2x + 1 and g(x) = x^2, find f(g(3)).','19'),
('functions-graphs','Functions & Graphs','10-11','challenge','State the domain of f(x) = 1/(x − 4).','All real numbers except x = 4'),
('functions-graphs','Functions & Graphs','10-11','challenge','If f(x) = 2^x, find f(0) + f(1) + f(2) + f(3).','15'),
('sequences-series','Sequences & Series','10-11','easy','Find the next term: 3, 7, 11, 15, …','19'),
('sequences-series','Sequences & Series','10-11','easy','Find the next term: 2, 6, 18, 54, …','162'),
('sequences-series','Sequences & Series','10-11','easy','Find the common difference of 12, 9, 6, 3, …','−3'),
('sequences-series','Sequences & Series','10-11','medium','Find the 15th term of the arithmetic sequence 7, 10, 13, …','49'),
('sequences-series','Sequences & Series','10-11','medium','Find the sum of the first 20 natural numbers.','210'),
('sequences-series','Sequences & Series','10-11','medium','Which term of the sequence 5, 8, 11, … is 62?','20th term'),
('sequences-series','Sequences & Series','10-11','challenge','Find the sum of the first 15 terms of an arithmetic sequence with first term 3 and common difference 5.','570'),
('sequences-series','Sequences & Series','10-11','challenge','Three numbers in arithmetic progression add up to 27, and the product of the first and last is 65. Find the numbers.','5, 9, 13'),
('sequences-series','Sequences & Series','10-11','challenge','In a geometric sequence the first term is 2 and the 4th term is 54. Find the common ratio.','3'),
('statistics','Statistics','10-11','easy','Find the mean of 6, 8, 10, 12, 14.','10'),
('statistics','Statistics','10-11','easy','Find the mode of 2, 3, 3, 4, 5, 3.','3'),
('statistics','Statistics','10-11','easy','Find the median of 5, 1, 9.','5'),
('statistics','Statistics','10-11','medium','Find the mean of the first 10 natural numbers.','5.5'),
('statistics','Statistics','10-11','medium','The mean of 5 observations is 18. Four of them are 15, 20, 22 and 12. Find the fifth.','21'),
('statistics','Statistics','10-11','medium','Find the median of 3, 8, 12, 5, 10, 15.','9'),
('statistics','Statistics','10-11','challenge','The mean of 20 numbers is 45. It is later found that one number was read as 25 instead of 52. Find the correct mean.','46.35'),
('statistics','Statistics','10-11','challenge','The mean of x, x + 2, x + 4, x + 6 and x + 8 is 11. Find x.','x = 7'),
('statistics','Statistics','10-11','challenge','Using the relation mode = 3(median) − 2(mean), find the mode when the median is 20 and the mean is 18.','24'),
('fractions-decimals','Fractions & Decimals','6-7','easy','What is 1/2 + 1/4?','3/4'),
('fractions-decimals','Fractions & Decimals','6-7','easy','Write 0.75 as a fraction in lowest terms.','3/4'),
('fractions-decimals','Fractions & Decimals','6-7','easy','Which is greater: 2/3 or 3/5?','2/3'),
('fractions-decimals','Fractions & Decimals','6-7','medium','A ribbon is 4.5 m long. If 1.8 m is cut off, how much ribbon remains?','2.7 m'),
('fractions-decimals','Fractions & Decimals','6-7','medium','Simplify: 3/4 × 8/9','2/3'),
('fractions-decimals','Fractions & Decimals','6-7','medium','Arrange in ascending order: 0.3, 1/4, 0.35','1/4, 0.3, 0.35'),
('fractions-decimals','Fractions & Decimals','6-7','challenge','A tank is 1/4 full. After adding 30 litres of water it becomes 3/4 full. What is the capacity of the tank?','60 litres'),
('fractions-decimals','Fractions & Decimals','6-7','challenge','What is 2.4 ÷ 0.06?','40'),
('fractions-decimals','Fractions & Decimals','6-7','challenge','A student reads 1/3 of a book on Monday and 1/4 of it on Tuesday. What fraction of the book is left?','5/12'),
('integers','Integers','6-7','easy','What is (−7) + 12?','5'),
('integers','Integers','6-7','easy','The temperature falls from 4°C to −3°C. By how many degrees did it fall?','7 degrees'),
('integers','Integers','6-7','easy','What is (−6) × (−3)?','18'),
('integers','Integers','6-7','medium','Find the value of (−15) + 8 − (−7).','0'),
('integers','Integers','6-7','medium','A submarine is at −45 m. It rises 18 m. What is its new position?','−27 m'),
('integers','Integers','6-7','medium','What is (−48) ÷ 6 − (−2)?','−6'),
('integers','Integers','6-7','challenge','In a quiz, each correct answer scores +5 and each wrong answer scores −2. A student answers 12 questions: 8 correct and 4 wrong. What is the score?','32'),
('integers','Integers','6-7','challenge','What is the sum of all integers from −10 to 12?','23'),
('integers','Integers','6-7','challenge','The product of three integers is −24. Two of them are −2 and 3. What is the third?','4'),
('ratio-proportion','Ratio & Proportion','6-7','easy','Simplify the ratio 12 : 18.','2 : 3'),
('ratio-proportion','Ratio & Proportion','6-7','easy','Three identical notebooks weigh 450 g in total. What does one notebook weigh?','150 g'),
('ratio-proportion','Ratio & Proportion','6-7','easy','Divide 20 sweets between two friends in the ratio 2 : 3. How many does each get?','8 and 12'),
('ratio-proportion','Ratio & Proportion','6-7','medium','A map uses the scale 1 cm : 5 km. What real distance does 7.5 cm on the map represent?','37.5 km'),
('ratio-proportion','Ratio & Proportion','6-7','medium','If a : b = 3 : 4 and b = 20, find a.','15'),
('ratio-proportion','Ratio & Proportion','6-7','medium','A recipe for 4 people uses 300 g of rice. How much rice is needed for 10 people?','750 g'),
('ratio-proportion','Ratio & Proportion','6-7','challenge','The ages of two children are in the ratio 5 : 7 and their ages add up to 48 years. Find their ages.','20 years and 28 years'),
('ratio-proportion','Ratio & Proportion','6-7','challenge','8 workers can finish a job in 15 days. Working at the same rate, how many days would 12 workers take?','10 days'),
('ratio-proportion','Ratio & Proportion','6-7','challenge','If 4 : x = x : 25, find the positive value of x.','10'),
('percentages','Percentages','6-7','easy','What is 25% of 80?','20'),
('percentages','Percentages','6-7','easy','Write 3/5 as a percentage.','60%'),
('percentages','Percentages','6-7','easy','10% of a number is 7. What is the number?','70'),
('percentages','Percentages','6-7','medium','A student scores 36 out of 40 in a test. What percentage is this?','90%'),
('percentages','Percentages','6-7','medium','A price of 500 increases by 12%. What is the new price?','560'),
('percentages','Percentages','6-7','medium','In a class of 40 students, 65% are girls. How many boys are in the class?','14'),
('percentages','Percentages','6-7','challenge','A price rises by 20% and then falls by 20%. What is the overall percentage change?','4% decrease'),
('percentages','Percentages','6-7','challenge','After a 15% discount, an item costs 340. What was the original price?','400'),
('percentages','Percentages','6-7','challenge','A town''s population grows from 8000 to 9200. What is the percentage increase?','15%'),
('simple-equations','Simple Equations','6-7','easy','Solve: x + 7 = 15','x = 8'),
('simple-equations','Simple Equations','6-7','easy','Solve: 3x = 21','x = 7'),
('simple-equations','Simple Equations','6-7','easy','Solve: x − 9 = −4','x = 5'),
('simple-equations','Simple Equations','6-7','medium','Solve: 2x + 5 = 17','x = 6'),
('simple-equations','Simple Equations','6-7','medium','Solve: x/4 − 3 = 2','x = 20'),
('simple-equations','Simple Equations','6-7','medium','Solve: 5(x − 2) = 30','x = 8'),
('simple-equations','Simple Equations','6-7','challenge','The sum of three consecutive whole numbers is 72. Find the numbers.','23, 24, 25'),
('simple-equations','Simple Equations','6-7','challenge','Solve: 7x − 4 = 3x + 16','x = 5'),
('simple-equations','Simple Equations','6-7','challenge','A number is doubled and increased by 9. The result equals 33 minus the number. Find the number.','8'),
('perimeter-area','Perimeter & Area','6-7','easy','Find the perimeter of a rectangle 8 cm long and 5 cm wide.','26 cm'),
('perimeter-area','Perimeter & Area','6-7','easy','Find the area of a square with side 9 cm.','81 cm²'),
('perimeter-area','Perimeter & Area','6-7','easy','The perimeter of a square is 36 cm. What is the length of one side?','9 cm'),
('perimeter-area','Perimeter & Area','6-7','medium','Find the area of a triangle with base 10 cm and height 6 cm.','30 cm²'),
('perimeter-area','Perimeter & Area','6-7','medium','A rectangle has an area of 48 cm² and a length of 8 cm. Find its width.','6 cm'),
('perimeter-area','Perimeter & Area','6-7','medium','Find the circumference of a circle with radius 7 cm. (Use π = 22/7)','44 cm'),
('perimeter-area','Perimeter & Area','6-7','challenge','A wire is bent into a square of side 11 cm. The same wire is re-bent into a circle. Find the radius of the circle. (Use π = 22/7)','7 cm'),
('perimeter-area','Perimeter & Area','6-7','challenge','A rectangular park is 60 m by 40 m. A 2 m wide path runs inside along the boundary. Find the area of the path.','384 m²'),
('perimeter-area','Perimeter & Area','6-7','challenge','If the side of a square is doubled, how many times larger does its area become?','4 times'),
('data-graphs','Data & Graphs','6-7','easy','Find the mean of 4, 8, 6, 2.','5'),
('data-graphs','Data & Graphs','6-7','easy','Find the mode of 3, 5, 5, 7, 8.','5'),
('data-graphs','Data & Graphs','6-7','easy','Find the range of 12, 7, 15, 9.','8'),
('data-graphs','Data & Graphs','6-7','medium','Find the median of 7, 3, 9, 5, 11.','7'),
('data-graphs','Data & Graphs','6-7','medium','The mean of five numbers is 12. Four of them are 10, 14, 9 and 13. Find the fifth number.','14'),
('data-graphs','Data & Graphs','6-7','medium','In a bar graph, 1 unit stands for 5 students. A bar is 6 units tall. How many students does it show?','30'),
('data-graphs','Data & Graphs','6-7','challenge','The mean of 6 numbers is 15. When one number, 20, is removed, what is the mean of the remaining numbers?','14'),
('data-graphs','Data & Graphs','6-7','challenge','Find the median of 4, 4, 6, 8, 10, 12.','7'),
('data-graphs','Data & Graphs','6-7','challenge','A die is rolled once. What is the probability of getting a number greater than 4?','1/3'),
('linear-equations','Linear Equations','8-9','easy','Solve: 2x + 3 = 11','x = 4'),
('linear-equations','Linear Equations','8-9','easy','Solve: 5x − 7 = 18','x = 5'),
('linear-equations','Linear Equations','8-9','easy','Solve: x/3 + 2 = 7','x = 15'),
('linear-equations','Linear Equations','8-9','medium','Solve: 3(x + 4) = 2x + 20','x = 8'),
('linear-equations','Linear Equations','8-9','medium','Solve: (2x − 1)/3 = 5','x = 8'),
('linear-equations','Linear Equations','8-9','medium','Two numbers differ by 6 and add up to 40. Find the numbers.','17 and 23'),
('linear-equations','Linear Equations','8-9','challenge','A two-digit number has digits that add up to 9. Reversing its digits increases the number by 27. Find the number.','36'),
('linear-equations','Linear Equations','8-9','challenge','Solve: (x + 2)/4 − (x − 1)/6 = 1','x = 4'),
('linear-equations','Linear Equations','8-9','challenge','A is twice as old as B. Five years ago, A was three times as old as B. Find their present ages.','A = 20, B = 10'),
('exponents','Exponents & Powers','8-9','easy','Find the value of 2^5.','32'),
('exponents','Exponents & Powers','8-9','easy','Simplify: 3^2 × 3^3','3^5 = 243'),
('exponents','Exponents & Powers','8-9','easy','What is the value of 10^0?','1'),
('exponents','Exponents & Powers','8-9','medium','Simplify: (2^3)^2','64'),
('exponents','Exponents & Powers','8-9','medium','Find the value of 5^−2.','1/25'),
('exponents','Exponents & Powers','8-9','medium','Express 0.00042 in standard form.','4.2 × 10^−4'),
('exponents','Exponents & Powers','8-9','challenge','Simplify: (2^4 × 2^6) ÷ 2^8','4'),
('exponents','Exponents & Powers','8-9','challenge','If 2^x = 64, find x.','x = 6'),
('exponents','Exponents & Powers','8-9','challenge','Find the value of (3/4)^−2.','16/9'),
('polynomials','Polynomials & Factoring','8-9','easy','Add: (3x + 5) + (2x − 3)','5x + 2'),
('polynomials','Polynomials & Factoring','8-9','easy','Multiply: 4x × 3x^2','12x^3'),
('polynomials','Polynomials & Factoring','8-9','easy','Factorise: 6x + 9','3(2x + 3)'),
('polynomials','Polynomials & Factoring','8-9','medium','Expand: (x + 3)(x + 5)','x^2 + 8x + 15'),
('polynomials','Polynomials & Factoring','8-9','medium','Factorise: x^2 − 25','(x − 5)(x + 5)'),
('polynomials','Polynomials & Factoring','8-9','medium','Factorise: x^2 + 7x + 12','(x + 3)(x + 4)'),
('polynomials','Polynomials & Factoring','8-9','challenge','Factorise: 2x^2 + 7x + 3','(2x + 1)(x + 3)'),
('polynomials','Polynomials & Factoring','8-9','challenge','If x + 1/x = 4, find the value of x^2 + 1/x^2.','14'),
('polynomials','Polynomials & Factoring','8-9','challenge','Expand and simplify: (x + 2)^2 − (x − 2)^2','8x'),
('triangles-circles','Triangles & Circles','8-9','easy','Two angles of a triangle are 65° and 45°. Find the third angle.','70°'),
('triangles-circles','Triangles & Circles','8-9','easy','A right triangle has legs 3 cm and 4 cm. Find the hypotenuse.','5 cm'),
('triangles-circles','Triangles & Circles','8-9','easy','What is the measure of each angle of an equilateral triangle?','60°'),
('triangles-circles','Triangles & Circles','8-9','medium','A right triangle has hypotenuse 13 cm and one leg 5 cm. Find the other leg.','12 cm'),
('triangles-circles','Triangles & Circles','8-9','medium','An exterior angle of a triangle is 110° and one interior opposite angle is 60°. Find the other interior opposite angle.','50°'),
('triangles-circles','Triangles & Circles','8-9','medium','The angles of a triangle are in the ratio 2 : 3 : 4. Find all three angles.','40°, 60°, 80°'),
('triangles-circles','Triangles & Circles','8-9','challenge','A 10 m ladder leans against a wall with its foot 6 m from the wall. How high up the wall does it reach?','8 m'),
('triangles-circles','Triangles & Circles','8-9','challenge','In an isosceles triangle the vertex angle is 40°. Find each base angle.','70°'),
('triangles-circles','Triangles & Circles','8-9','challenge','What is the measure of an angle drawn in a semicircle (subtended by the diameter)?','90°'),
('mensuration','Surface Area & Volume','8-9','easy','Find the volume of a cube with side 4 cm.','64 cm³'),
('mensuration','Surface Area & Volume','8-9','easy','Find the volume of a cuboid 5 cm × 3 cm × 2 cm.','30 cm³'),
('mensuration','Surface Area & Volume','8-9','easy','Find the total surface area of a cube with side 3 cm.','54 cm²'),
('mensuration','Surface Area & Volume','8-9','medium','Find the total surface area of a cuboid 4 cm × 3 cm × 2 cm.','52 cm²'),
('mensuration','Surface Area & Volume','8-9','medium','Find the volume of a cylinder with radius 7 cm and height 10 cm. (Use π = 22/7)','1540 cm³'),
('mensuration','Surface Area & Volume','8-9','medium','A cube has a volume of 125 cm³. Find the length of one side.','5 cm'),
('mensuration','Surface Area & Volume','8-9','challenge','How many cubes of side 2 cm can fit exactly inside a box measuring 6 cm × 4 cm × 2 cm?','6'),
('mensuration','Surface Area & Volume','8-9','challenge','Find the curved surface area of a cylinder with radius 7 cm and height 15 cm. (Use π = 22/7)','660 cm²'),
('mensuration','Surface Area & Volume','8-9','challenge','A cuboid-shaped tank measures 2 m × 1.5 m × 1 m. How many litres of water can it hold? (1 m³ = 1000 L)','3000 litres'),
('probability-stats','Probability & Statistics','8-9','easy','A fair coin is tossed once. What is the probability of getting heads?','1/2'),
('probability-stats','Probability & Statistics','8-9','easy','A die is rolled once. What is the probability of getting an even number?','1/2'),
('probability-stats','Probability & Statistics','8-9','easy','Find the mean of 5, 10, 15.','10'),
('probability-stats','Probability & Statistics','8-9','medium','A bag contains 3 red and 5 blue balls. One ball is drawn at random. What is the probability it is red?','3/8'),
('probability-stats','Probability & Statistics','8-9','medium','Cards numbered 1 to 10 are shuffled and one is drawn. What is the probability of drawing a multiple of 3?','3/10'),
('probability-stats','Probability & Statistics','8-9','medium','Find the median of 12, 5, 8, 15, 10.','10'),
('probability-stats','Probability & Statistics','8-9','challenge','Two fair coins are tossed together. What is the probability of getting exactly one head?','1/2'),
('probability-stats','Probability & Statistics','8-9','challenge','The mean of 10 numbers is 20. If each number is increased by 5, what is the new mean?','25'),
('probability-stats','Probability & Statistics','8-9','challenge','Two dice are rolled together. What is the probability that the sum is 7?','1/6'),
('money-problems','Money Problems','8-9','easy','An item is bought for 200 and sold for 250. Find the profit.','50'),
('money-problems','Money Problems','8-9','easy','Find the simple interest on 1000 at 5% per year for 2 years.','100'),
('money-problems','Money Problems','8-9','easy','A 10% discount is given on a marked price of 450. How much does the customer pay?','405'),
('money-problems','Money Problems','8-9','medium','An item bought for 400 is sold for 460. Find the profit percentage.','15%'),
('money-problems','Money Problems','8-9','medium','Find the simple interest on 2500 at 8% per year for 3 years.','600'),
('money-problems','Money Problems','8-9','medium','An item is sold for 540 at a loss of 10%. Find the cost price.','600'),
('money-problems','Money Problems','8-9','challenge','Successive discounts of 20% and then 10% are given on a marked price of 500. Find the final price.','360'),
('money-problems','Money Problems','8-9','challenge','In how many years will 4000 grow to 5000 at 5% per year simple interest?','5 years'),
('money-problems','Money Problems','8-9','challenge','The cost price of 12 items equals the selling price of 10 items. Find the profit percentage.','20%');
